# -*- coding: utf-8 -*-
"""
Created on Fri Sep 13 10:36:19 2013

@author: lucab0ni

Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""
import dis

def fibo_sum():
    a = 1
    b = 1
    s = 0

    while True:
        # Swapping values without using a temporary variable
        a, b = b, a + b

        if b < 4000000:
            if not(b % 2):
                s += b
        else:
            break
    return s

sum = fibo_sum()
print "The answer is ", sum

# Use of disassembler module. It converts byte codes to a format that is
# slightly more appropriate for human consumption.
dis.dis(fibo_sum)

# 4613732