# -*- coding: utf-8 -*-
"""
Created on Fri Sep 13 10:36:19 2013

@author: lucab0ni

Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""

fiboNr_a = 1
fiboNr_b = 2
temp = 0
sum = fiboNr_b

while True:
    temp = fiboNr_b
    fiboNr_b = fiboNr_a + fiboNr_b
    fiboNr_a = temp
    
    if fiboNr_b < 4000000:
        print "next Fibonacci number ", fiboNr_b
        if not(fiboNr_b % 2):
            sum += fiboNr_b
    else:
        break
   
print sum

# 4613732